# Site settings
title: Abstract Nonsense
email: roycroft16c@gmail.com
description: "Chase's blog"
##baseurl: "/MathJax-website"
#url: "http://www.mathjax.org"
author: Chase Roycroft
TimeZone: America/New_York

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
