markdown: kramdown

# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://chaseroycroft.github.io"


# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-84149519-1"
# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Chase Roycroft"
title: "Chase Roycroft"
description: "Blog and website of Chase Roycroft. Opinions expressed are mine."
keywords: "chase, roycroft, personal, blog, quantum, gravity, technology"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/coffee.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "My goal is to understand the nature of existence, and to engineer improvements thereupon."
  - text: "Nothing in life is to be feared; it is only to be understood. Now is the time to understand more, so that we may fear less."
  - text: "For me, it is far better to grasp the Universe as it really is than to persist in delusion, however satisfying and reassuring."
  - text: "The armies of the world cannot stop an idea whose time has come."






me-img: "/img/profile.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 150

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname: "chaseroycroft"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timelnie/death.png"
  - date: "???"
  - description: "my eventual death"

#  - image: "/img/timeline/unclogo.jpg"
#    date: "2016 - 2020"
#    description: "Undergrad at UNC-CH"
  - image: "/img/timeline/ncssmlogo.jpg"
    date: "2014 - 2016"
    description: "NCSSM"
#  - image: "/img/timeline/enloelogo.png"
#    date: "2012-2014"
#    description: "Enloe"
  - image: "/img/timeline/baby.png"
    date: "February 1998"
    description: "Born"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "roycroft16c@gmail.com"
email: "chaser.live.unc.edu"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/chaseroycroft.1"
  - title: "twitter"
    url: "https://twitter.com/chaseroycroft"
  - title: "github"
    url: "https://github.com/chaseroycroft"
  - title: "linkedin"
    url: "https://linkedin.com/in/chaseroycroft"
  - title: "instagram"
    url: "https://www.instagram.com/chaseroycroft/"
  - title: "pinterest"
    url: "https://pinterest.com/chaseroycroft"
  - title: "Atom/RSS"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Tags: 'tag-cloud'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
