# Site settings
title: MathJax
email: info@mathjax.org
description: "Beautiful math in all browsers."
##baseurl: "/MathJax-website"
url: "http://www.mathjax.org"
author: MathJax Consortium
TimeZone: America/New_York

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
